# Generated by Django 4.2.8 on 2024-01-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=30, null=True)),
                ('payment_id', models.CharField(max_length=30, null=True)),
                ('mihpay_id', models.CharField(max_length=30, null=True)),
                ('payu_status', models.BooleanField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Initiated'), (1, 'Paid'), (2, 'Cancelled'), (3, 'Failed'), (4, 'Refund_initiated'), (5, 'Refund_finished')], default=0)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('error_code', models.CharField(max_length=255, null=True)),
                ('error_message', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('payment_mode', models.CharField(max_length=255, null=True)),
                ('payment_added_on', models.DateTimeField(null=True)),
                ('pg_type', models.CharField(max_length=255, null=True)),
                ('bank_refnum', models.CharField(max_length=255, null=True)),
                ('refund_amount', models.IntegerField(default=0, null=True)),
                ('additional_charges', models.FloatField(default=0, null=True)),
                ('field9', models.TextField(max_length=512, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_paid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
