# Generated by Django 4.2.9 on 2024-01-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'ONLINE'), (1, 'MAINTENANCE')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=30, null=True)),
                ('payment_id', models.CharField(max_length=30, null=True)),
                ('mihpay_id', models.CharField(max_length=30, null=True)),
                ('payu_status', models.BooleanField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Initiated'), (1, 'Paid'), (2, 'Cancelled'), (3, 'Failed'), (4, 'Refund_initiated'), (5, 'Refund_finished')], default=0)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('error_code', models.CharField(max_length=255, null=True)),
                ('error_message', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('payment_mode', models.CharField(max_length=255, null=True)),
                ('payment_added_on', models.DateTimeField(null=True)),
                ('pg_type', models.CharField(max_length=255, null=True)),
                ('bank_refnum', models.CharField(max_length=255, null=True)),
                ('refund_amount', models.IntegerField(default=0, null=True)),
                ('additional_charges', models.FloatField(default=0, null=True)),
                ('field9', models.TextField(max_length=512, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_paid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('bay', models.CharField(blank=True, max_length=40, null=True)),
                ('is_filled', models.BooleanField(blank=True, default=False, null=True)),
                ('max_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_early_bird', models.BooleanField(blank=True, default=False, null=True)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('is_transport_needed', models.BooleanField(blank=True, default=False, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('jnm_id', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_changed', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.tickets')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
