# Generated by Django 4.2.9 on 2024-01-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jnm_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
