# Generated by Django 4.2.9 on 2024-01-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_profile_is_transport_needed_alter_profile_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_changed', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.transaction')),
            ],
        ),
    ]
