# Generated by Django 4.2.9 on 2024-01-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_profile_is_transport_needed_alter_profile_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bay',
            field=models.PositiveSmallIntegerField(choices=[(250, 'Seated'), (200, 'First Bay'), (150, 'Second Bay')], default=250),
        ),
    ]
