# Generated by Django 4.2.9 on 2024-01-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_profile_bay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bay',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(250, 'Seated'), (200, 'First Bay'), (150, 'Second Bay')], null=True),
        ),
    ]
