# Generated by Django 4.2.9 on 2024-01-03 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0006_alter_profile_bay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bay',
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.PositiveSmallIntegerField(blank=True, choices=[(250, 'Seated'), (200, 'First Bay'), (150, 'Second Bay')], null=True)),
                ('is_filled', models.BooleanField(blank=True, default=False, null=True)),
                ('is_early_bird', models.BooleanField(blank=True, default=False, null=True)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
