# Generated by Django 4.2.9 on 2024-01-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_remove_profile_bay_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.tickets'),
        ),
    ]
