# Generated by Django 4.2.9 on 2024-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_profile_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='bay',
            field=models.CharField(blank=True, choices=[(250, 'Seated'), (200, 'First Bay'), (150, 'Second Bay')], max_length=30, null=True),
        ),
    ]
