# Generated by Django 4.2.9 on 2024-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_tickets_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='max_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
