# Generated by Django 4.2.9 on 2024-01-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_tickets_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='bay',
            field=models.CharField(blank=True, choices=[('SEATED', 'Seated'), ('FIRST_BAY', 'First Bay'), ('SECOND_BAY', 'Second Bay')], max_length=30, null=True),
        ),
    ]
