# Generated by Django 4.2.9 on 2024-01-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_tickets_price_alter_tickets_bay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='bay',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
