# Generated by Django 4.2.9 on 2024-01-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_checkstatuslog'),
        ('base_app', '0012_alter_tickets_bay'),
    ]

    operations = [
    ]
