# Generated by Django 4.2.9 on 2024-01-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_merge_0005_checkstatuslog_0012_alter_tickets_bay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ticket',
        ),
        migrations.AddField(
            model_name='checkstatuslog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.tickets'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.tickets'),
        ),
    ]
